micronaut:
  application:
    name: ${project.artifactId}
  #  server:
  #    port: 9090

  http:
    services:
      orion:
        path: ngsi-ld/v1
        url: http://localhost:1026

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

jackson:
  date-format: YYYY-MM-dd'T'hh:mm:ss.ssss
  time-zone: UTC
  serializationInclusion: NON_NULL
  serialization:
    indentOutput: true


endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

simulator:
  companies:
    - name: company-1
      cranes:
        - name: crane-c1-1
          model: "Euro SSG 130"
        - name: crane-c2-1
          model: "Euro SSG 130"
          latitude: 51.14
          longitude: 13.7
#        - name: crane-c1-2
#        - name: crane-c1-3
#        - name: crane-c1-4
#        - name: crane-c1-5
#    - name: company-2
#      cranes:
#        - name: crane-c2-1
#        - name: crane-c2-2
#        - name: crane-c2-3
#    - name: company-3
#      cranes:
#        - name: crane-c3-1
#        - name: crane-c3-2
#        - name: crane-c3-3